name: Build and Test

on:
  push:
    branches: [ main, order-split ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test --if-present
    
    - name: Build application
      run: npm run build
    
    - name: Create deployment package
      run: |
        mkdir deployment-package
        cp -r dist/* deployment-package/
        cp package.json deployment-package/
        cp ecosystem.config.cjs deployment-package/
        cd deployment-package
        zip -r ../hyperliquid-build-$(date +%Y%m%d-%H%M%S).zip .
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: hyperliquid-deployment-${{ github.sha }}
        path: hyperliquid-build-*.zip
        retention-days: 30
    
    - name: Deployment Instructions
      run: |
        echo "🚀 Build completed successfully!"
        echo ""
        echo "To deploy manually:"
        echo "1. Download the build artifact from this workflow"
        echo "2. Run the interactive deployment script:"
        echo "   ./interactive-deploy.ps1"
        echo ""
        echo "Or use the secure manual deployment process described in the README."

